package(default_visibility = ["//visibility:public"])

exports_files([

  "haskell.bzl",
  "repositories.bzl",
  "cc.bzl",
  "haddock.bzl",
  "toolchain.bzl",
  "ghc_bindist.bzl",
  "binutils-repo.bzl",

  "ghc-defs-cleanup.sh",
  "ghc-version-check.sh",

])
