templates = {
    "happy": [
        "GLR_Base",
        "HappyTemplate-arrays-coerce-debug",
        "GLR_Lib",
        "HappyTemplate-arrays-debug",
        "GLR_Lib-ghc",
        "HappyTemplate-arrays-ghc",
        "GLR_Lib-ghc-debug",
        "HappyTemplate-arrays-ghc-debug",
        "HappyTemplate",
        "HappyTemplate-coerce",
        "HappyTemplate-arrays",
        "HappyTemplate-ghc",
        "HappyTemplate-arrays-coerce",
    ],
    "alex": [
        "AlexTemplate",
        "AlexTemplate-debug",
        "AlexTemplate-ghc",
        "AlexTemplate-ghc-debug",
        "AlexTemplate-ghc-nopred",
        "AlexWrapper-basic",
        "AlexWrapper-basic-bytestring",
        "AlexWrapper-gscan",
        "AlexWrapper-monad",
        "AlexWrapper-monad-bytestring",
        "AlexWrapper-monadUserState",
        "AlexWrapper-monadUserState-bytestring",
        "AlexWrapper-posn",
        "AlexWrapper-posn-bytestring",
        "AlexWrapper-strict-bytestring",
    ],
}
