pull_request_rules:
  - name: automatic merge
    conditions:
      - "status-success=build"
      - "#approved-reviews-by>=1"
      - "label=merge-queue"
      - "base=master"
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: smart
        strict_method: merge
  - name: delete head branch after merge
    conditions:
      - merged
      - closed
    actions:
      delete_head_branch: {}
  - name: remove from merge-queue after merge
    conditions:
      - merged
    actions:
      label:
        remove:
          - "merge-queue"
