queue_rules:
  - name: default
    queue_conditions:
      - "label=merge-queue"
      - "base=master"
    merge_conditions: []
    merge_method: merge

pull_request_rules:
  - name: delete head branch after merge
    conditions:
      - merged
      - closed
    actions:
      delete_head_branch: {}
  - name: remove from merge-queue after merge
    conditions:
      - merged
    actions:
      label:
        remove:
          - "merge-queue"
  - name: automatic merge
    conditions: []
    actions:
      queue:
