pull_request_rules:
  - name: automatic merge
    conditions:
      - "status-success=build"
      - "#approved-reviews-by>=1"
      - "label=merge-queue"
      - "base=master"
    actions:
      merge:
        method: merge
        strict: smart
  - name: remove from merge-queue after merge
    conditions:
      - merged
    actions:
      label:
        remove:
          - "merge-queue"
