
pull_request_rules:
  - name: automatic merge
    conditions:
      - "label=merge-queue"
      - "base=master"
    actions:
      queue:
        name: default
        method: merge

  - name: delete head branch after merge
    conditions:
      - merged
      - closed
    actions:
      delete_head_branch: {}

  - name: remove from merge-queue after merge
    conditions:
      - merged
    actions:
      label:
        remove:
          - "merge-queue"
