# Container for https://haskell.build.

FROM ubuntu:xenial

RUN apt-get update && apt-get install -y curl \
    && echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" \
    | tee /etc/apt/sources.list.d/bazel.list \
    && curl https://bazel.build/bazel-release.pub.gpg | apt-key add - \
    && apt-get update \
    && apt-get install -y \
         bazel \
	 openjdk-8-jdk \
	 python \
	 unzip

COPY WORKSPACE /bazel/
COPY start /bazel/
COPY haskell /bazel/haskell/
COPY skylark /bazel/skylark/
COPY docs /bazel/docs/
COPY tests /bazel/tests/

RUN cd /bazel; bazel build //docs
RUN unzip -d /site /bazel/bazel-bin/docs/docs-skydoc.zip \
    && cp /bazel/start /site

CMD cd /site; python -m SimpleHTTPServer $PORT
