[build]
command = ".netlify/install.sh && .netlify/build.sh"
publish = "public"

[context.production.environment]
  RENDER_GUIDE = "false"

[context.deploy-preview.environment]
  RENDER_GUIDE = "true"