cc_library(
    name = "value",
    srcs = ["value.c"],
    visibility = ["//tests/binary-with-doubly-indirect-cbits:__subpackages__"],
    deps = ["//tests/binary-with-doubly-indirect-cbits/lib-indirect:add"],
)
