local_repository(
    name = "rules_haskell",
    path = "%RULES_HASKELL_PATH%",
)

load("@rules_haskell//haskell:repositories.bzl", "rules_haskell_dependencies")

rules_haskell_dependencies()

load("@rules_haskell//haskell:nixpkgs.bzl", "haskell_register_ghc_nixpkgs")

haskell_register_ghc_nixpkgs(
    attribute_path = "",
    nix_file_content = "with import <nixpkgs> {}; haskell.packages.ghc948.ghcWithPackages (p:[p.async])",
    repository = "@rules_haskell//nixpkgs:default.nix",
    version = "9.4.8",
)

load(
    "@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl",
    "nixpkgs_cc_configure",
    "nixpkgs_python_configure",
)

nixpkgs_cc_configure(
    name = "nixpkgs_config_cc",
    cc_std = "c++14",
    repository = "@rules_haskell//nixpkgs:default.nix",
)

load("@bazel_features//:deps.bzl", "bazel_features_deps")

bazel_features_deps()

load("@rules_cc//cc:extensions.bzl", "compatibility_proxy_repo")

compatibility_proxy_repo()

nixpkgs_python_configure(
    repository = "@rules_haskell//nixpkgs:default.nix",
)
