#!/usr/bin/env bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# nixpkgs Bazel version ends on '- (@non-git)'.
VERSION_EXPECTED="bazel $(cat "$DIR/bazel-version")- (@non-git)"
VERSION_ACTUAL=$(bazel version --gnu_format)
[[ "$VERSION_ACTUAL" = "$VERSION_EXPECTED" ]] || {
  echo "Expected Bazel version $VERSION_EXPECTED but found $VERSION_ACTUAL." >&2
  exit 1
}
