#!/usr/bin/env bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

VERSION=$(cat "$DIR/bazel-version")
INSTALL="$(mktemp -d)"
curl -L "https://github.com/bazelbuild/bazel/releases/download/$VERSION/bazel-$VERSION-linux-x86_64" -o "$INSTALL/bazel" >&2
(cd "$INSTALL" && sha256sum --quiet -c "$DIR/bazel-sha256") >&2
chmod +x "$INSTALL/bazel"
echo -n "$INSTALL"
