steps:
  - label: "Run tests (Nixpkgs)"
    command: |
      . /var/lib/buildkite-agent/.nix-profile/etc/profile.d/nix.sh
      echo "build:ci --host_platform=@rules_haskell//haskell/platforms:linux_x86_64_nixpkgs" > .bazelrc.local
      nix-shell --arg docTools false --pure --run '
      set -e
      # Ensure that the Nixpkgs bazel version matches the one specified in
      # `.buildkite/bazel-version` and fetched in
      # `.buildkite/bindists-pipeline` for the bindists version.
      .buildkite/check-bazel-version
      ./tests/run-start-script.sh --use-nix
      bazel build --config ci --config ci_linux //tests:run-tests
      ./bazel-ci-bin/tests/run-tests
      bazel coverage //tests/... --config ci --config ci_linux --build_tag_filters "coverage-compatible" --test_tag_filters "coverage-compatible" --test_output=all
      '
    timeout: 100

  - label: "Run tests (bindists)"
    command: ".buildkite/bindists-pipeline"
    timeout: 100
