steps:
  - label: "Run tests (Nixpkgs)"
    command: |
      . /var/lib/buildkite-agent/.nix-profile/etc/profile.d/nix.sh
      echo "build:ci --host_platform=@rules_haskell//haskell/platforms:linux_x86_64_nixpkgs" > .bazelrc.local
      nix-shell --arg docTools false --pure --run '
      set -e
      ./tests/run-start-script.sh --use-nix
      bazel build --config ci //tests:run-tests
      ./bazel-ci-bin/tests/run-tests
      bazel coverage //tests/... --config ci --build_tag_filters "coverage-compatible" --test_tag_filters "coverage-compatible" --test_output=all
      '
    timeout: 30

  - label: "Run tests (bindists)"
    command: |
      echo "common:ci --build_tag_filters -requires_lz4,-requires_proto,-requires_zlib,-requires_doctest,-requires_c2hs,-requires_threaded_rts,-dont_test_with_bindist" > .bazelrc.local
      # XXX: See .bazelrc [backward compatible options] for the the rational behind this flag
      echo "build --incompatible_use_python_toolchains=false" >> .bazelrc.local
      ./tests/run-start-script.sh --use-bindists
      bazel build --config ci //tests/...
    timeout: 30
