workspace(name = "ai_formation_hazel")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "io_tweag_rules_nixpkgs",
    strip_prefix = "rules_nixpkgs-cd2ed701127ebf7f8f21d37feb1d678e4fdf85e5",
    urls = ["https://github.com/tweag/rules_nixpkgs/archive/cd2ed70.tar.gz"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository", "nixpkgs_package")

nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "ee80654b5267b07ba10d62d143f211e0be81549e",
)

load("//:cc_configure_custom.bzl", "cc_configure_custom")

nixpkgs_package(
    name = "compiler",
    nix_file = "//:compiler.nix",
    repository = "@nixpkgs",
)

nixpkgs_package(
    name = "binutils",
    attribute_path = "binutils",
    repository = "@nixpkgs",
)

cc_configure_custom(
    name = "local_config_cc",
    gcc = "@compiler//:bin/cc",
    ld = "@binutils//:bin/ld",
)

local_repository(
    name = "io_tweag_rules_haskell",
    path = "..",
)

load("@io_tweag_rules_haskell//haskell:repositories.bzl", "haskell_repositories")

haskell_repositories()

nixpkgs_package(
    name = "ghc",
    attribute_path = "haskell.packages.ghc822.ghc",
    build_file = "@ai_formation_hazel//:BUILD.ghc",
    repository = "@nixpkgs",
)

nixpkgs_package(
    name = "c2hs",
    attribute_path = "haskell.packages.ghc822.c2hs",
    repository = "@nixpkgs",
)

nixpkgs_package(
    name = "taglib",
    attribute_path = "taglib",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

load("@io_tweag_rules_haskell//haskell:haskell.bzl", "haskell_cc_import")

filegroup (
  name = "lib",
  srcs = glob([
    "lib/libtag_c.so",
    "lib/libtag_c.dylib",
  ]),
)
""",
    repository = "@nixpkgs",
)

nixpkgs_package(
    name = "libsndfile.out",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

filegroup(
  name = "lib",
  srcs = glob([
    "lib/libsndfile.so",
    "lib/libsndfile.dylib",
  ]),
)
""",
    repository = "@nixpkgs",
)

nixpkgs_package(
    name = "libsndfile.dev",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

filegroup(
  name = "headers",
  srcs = glob([
    "include/*.h",
  ]),
)
""",
    repository = "@nixpkgs",
)

nixpkgs_package(
    name = "postgresql",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

filegroup (
  name = "lib",
  srcs = glob([
    "lib/libecpg.so",
    "lib/libecpg.dylib",
  ]),
)

filegroup (
  name = "headers",
  srcs = glob([
    "include/*.h",
    "include/**/*.h",
  ]),
)
""",
    repository = "@nixpkgs",
)

nixpkgs_package(
    name = "glib_locales",
    attribute_path = "glibcLocales",
    build_file_content = """
package(default_visibility = ["//visibility:public"])

filegroup(
  name = "locale-archive",
  srcs = ["lib/locale/locale-archive"],
)
""",
    repository = "@nixpkgs",
)

register_toolchains(
    "@ghc//:ghc",
    "//:c2hs-toolchain",
    "//:doctest",
)

load(
    "//:hazel.bzl",
    "hazel_custom_package_github",
    "hazel_custom_package_hackage",
    "hazel_repositories",
)

hazel_custom_package_hackage(
    package_name = "zlib",
    version = "0.6.2",
)

hazel_custom_package_hackage(
    package_name = "zlib-bindings",
    version = "0.1.1.5",
)

hazel_custom_package_hackage(
    package_name = "vault",
    version = "0.3.1.1",
)

hazel_custom_package_hackage(
    package_name = "ghc-paths",
    version = "0.1.0.9",
)

hazel_custom_package_github(
    package_name = "text-metrics",
    github_repo = "text-metrics",
    github_user = "mrkkrp",
    repo_sha = "5d10b6f6ec4ff4b014e5e512f82d23e7606cc260",
)

hazel_custom_package_github(
    package_name = "conduit",
    github_repo = "conduit",
    github_user = "snoyberg",
    repo_sha = "34db9267bb4f9dbdee45623944900062e7995d09",
    strip_prefix = "conduit",
)

hazel_custom_package_github(
    package_name = "wai-app-static",
    github_repo = "wai",
    github_user = "FormationAI",
    repo_sha = "9217512fae1d6c2317447b257f478005efb55ef7",
    strip_prefix = "wai-app-static",
)

load("//:packages.bzl", "core_packages", "packages")

hazel_repositories(
    core_packages = core_packages,
    exclude_packages = [
        "conduit",
        "ghc-paths",
        "text-metrics",
        "vault",
        "wai-app-static",
        "zlib",
        "zlib-bindings",
    ],
    extra_libs = {
        "pq": "@//:pq",
        "sndfile": "@//:sndfile",
        "tag_c": "@//:tag_c",
    },
    packages = packages,
)
