package(default_visibility = ["//visibility:public"])

load(
  "@io_tweag_rules_haskell//haskell:haskell.bzl",
  "haskell_library",
)

haskell_library(
  name = 'one',
  srcs = [ 'One.hs' ]
)

haskell_library(
  name = 'two',
  srcs = [ 'Two.hs' ]
)
