#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

# This script is called by Bazel before executing the specified command.
# For more details:
# https://github.com/bazelbuild/bazel/blob/7f782e3c1a1c4a21beea19c2cedb614be8316e67/scripts/packages/bazel.sh#L34-L39

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"

common_sh="${script_dir}/common.sh"
# shellcheck source=SCRIPTDIR/common.sh
source "${common_sh}"
