#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null && pwd)"

common_sh="${script_dir}/../../tools/common.sh"
# shellcheck source=SCRIPTDIR/../../tools/common.sh
source "${common_sh}"
